updated pipelines

diff --git a/.azure-devops/main.yml b/.azure-devops/main.yml
--- a/.azure-devops/main.yml
+++ b/.azure-devops/main.yml
@@ -27,10 +27,6 @@ stages:
         Contents: '**\*.dacpac'
         TargetFolder: .publish-sql
 
-    # - script: |
-    #     scripts\publish-database.ps1
-    #   displayName: '.NET Publish'
-
     - publish: $(System.DefaultWorkingDirectory)\.publish-sql
       artifact: Dacpac
       displayName: 'Publish Artifact'
@@ -67,21 +63,29 @@ stages:
       artifact: Dacpac
       displayName: 'Dowload DACPAC artifact'
 
-    - script: |
-        #!/bin/bash
-        dacpac_path="$(Pipeline.Workspace)/Dacpac"
-        echo "Deploying DACPAC files from $dacpac_path"
-        for dacpac_file in $(find $dacpac_path -name '*.dacpac'); do
-          echo "Deploying $dacpac_file..."
-          sqlpackage /a:publish \
-            /TargetConnectionString:"$(connectionStrings__TestDatabase)" \
-            /SourceFile:"$dacpac_file"
-          if [ $? -ne 0 ]; then
-            echo "Deployment of $dacpac_file failed"
-            exit 1
-          fi
-        done
-      displayName: 'Deploy DACPAC(s)'
+    # - script: |
+    #     #!/bin/bash
+    #     dacpac_path="$(Pipeline.Workspace)/Dacpac"
+    #     echo "Deploying DACPAC files from $dacpac_path"
+    #     for dacpac_file in $(find $dacpac_path -name '*.dacpac'); do
+    #       echo "Deploying $dacpac_file..."
+    #       sqlpackage /a:publish \
+    #         /TargetConnectionString:"$(connectionStrings__TestDatabase)" \
+    #         /SourceFile:"$dacpac_file"
+    #       if [ $? -ne 0 ]; then
+    #         echo "Deployment of $dacpac_file failed"
+    #         exit 1
+    #       fi
+    #     done
+    #   displayName: 'Deploy DACPAC(s)'
+
+    -script: |
+      #!/bin/bash
+      dacpac_path="$(Pipeline.Workspace)/Dacpac/SocialMedia.Database.dacpac"
+      sqlpackage /a:publish \
+        /TargetConnectionString:"$(connectionStrings__TestDatabase)" \
+        /SourceFile:"$dacpac_file"
+      displayName: 'Deploy DACPAC'
 
     - script: |
         scripts/test.sh -configuration Release -nobuild
